version: '3'

# Microservices
services:
  # Postgresql database container
  db:
    image: postgres:latest
    container_name: stocks-postgres
    privileged: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks: 
      - stocks-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h stocks-postgres -U postgres -p 5432 | grep 'accepting connections'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  pgbouncer:
    build: ./pgbouncer
    container_name: pgbouncer
    image: bitnami/pgbouncer:latest
    environment:
      - AUTH_TYPE=trust
      - POOL_MODE=session
      - PGBOUNCER_MAX_CLIENT_CONN=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=123456
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - 6432:6432
    networks: 
      - stocks-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Core container
  core:
    build: ./src
    container_name: core-modules
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/workspace
    networks:
      - stocks-network
    depends_on:
      pgbouncer:
        condition: service_healthy

  # Streamlit app container
  web:
    build: ./streamlit
    container_name: streamlit-container
    ports: 
      - 8501:8501
    volumes:
      - ./streamlit:/app
    networks:
      - stocks-network
    depends_on:
        - core

# Shared network for microservices
networks:
  stocks-network:
    name: stocks-network
