site_name: Stock Tracker

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Stock Tracker Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
