name: ci
on:
  push:
    branches:
      - '*'
permissions:
  contents: write
jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs "mkdocstrings[python]" mkdocs-material
      - run: mkdocs gh-deploy --force

  mypy:
    needs: build
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install mypy
          mypy --install-types
      - name: mypy
        run: |
          mypy src/

  pylint:
    needs: build
    runs-on: ubuntu-latest
    name: pylint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install pylint
      - name: pylint
        run: |
          pylint src/

  pytest:
    needs: build
    runs-on: ubuntu-latest
    name: pytest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install pytest
      - name: pytest
        run: |
          pytest tests/